name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.V2_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.V2_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Package and deploy
        shell: bash
        run: |
          aws cloudformation package \
            --template-file cloudformation.yml \
            --s3-bucket cf-templates-aubvn3i9olmk-us-west-2 \
            --output-template-file packaged.yml
          aws cloudformation deploy \
            --stack-name legacy-domains \
            --template-file packaged.yml \
            --role-arn ${{ secrets.CLOUDFORMATION_ROLE_ARN }} \
            --capabilities CAPABILITY_IAM \
            --parameter-overrides \
                CertificateArn=${{ secrets.CERTIFICATE_ARN }}
